### ISSUE TITLE
More Flexible Components

### ISSUE THREAD

**Issue by colesanders** [GetStream/stream-chat-angular#251]
While using this library to add chat as a secondary feature to an existing app, we ended up having to create a handful of custom components to fulfill a similar use case to what's provided since the existing components weren't quite flexible enough. Currently it works great as a drop in solution. I was able to just follow the docs and add the components to the template and have it start working. However trying to implement a more custom user experience lead to writing custom components that serve nearly the same purpose, with minor changes.

### Channel Preview Component

The channel preview component takes a single channel as an input and that's really the only customizable piece of the component. The avatar, message preview, and unread indication doesn't allow for any slight changes. Of course if a developer needs absolute control over the display, then can use a custom component. But if only some slight tweaks are needed, that's really the only option. 

For the avatar image, if that was instead available as a slot (ie through an `<ng-content select="[slot=start]">`) or even an input ( either an ngTemplate or just a simple `[avatarImage]` Input that allowed the developer to override the default image) then that would allow much easier tweaks to the component. Personally I would recommend making it a slot, that way the developer could use whatever in place of the avatar such as an icon. Or just use the avatar component already available if they want the default functionality. 

```html
<stream-channel-preview [channel]="channel">
  <stream-avatar slot="start" [imageUrl]="someImageUrl"></stream-avatar>
</stream-channel-preview>
```

### Unread Count Component

As well, having a component that receives a channel as an input and conditionally shows a badge with the unread count would be super helpful. Continuing on the idea of slots above, having an "end" slot would allow for much more flexibility as well. Then the develop could slot the avatar image in the "end" slot to essentially reverse the display order. Or use the unread count component in the end slot as an additional indicator.

```html
<!-- Reversed content order -->
<stream-channel-preview [channel]="channel">
  <stream-avatar slot="end" [imageUrl]="someImageUrl"></stream-avatar>
</stream-channel-preview>

<!-- Added unread indicator -->
<stream-channel-preview [channel]="channel">
  <stream-avatar slot="start" [imageUrl]="someImageUrl"></stream-avatar>
  <stream-unread-badge slot="end" [channel]="channel"></stream-unread-badge>
</stream-channel-preview>
```

_As a note:
A lot of this advice comes from implementing stream-chat-angular in an Ionic application. Since Ionic uses slotting for their components to allow for flexibility, implementing a similar component structure would allow for more seamless integration with Ionic as well as standard angular apps. A developer in an Ionic app could then slot an ion-icon as the channel preview or conditionally show different icons in the end slot based on channel type._

### In General

I mostly discuss changes for the channel preview component, as that's the one we had to make a custom component for. But in general, implementing a more single responsibility component design would allow developer to make much better use of your library as the components are fairly intertwined. Another example would be how all the component pieces just sit in the `<stream-channel></stream-channel>` component in the template. Being able to separate those out into different places would make the library much more flexible. Then a developer could put the `message-list` and `message-input` components into a modal driven by whatever library the rest of their application is built on to show message. Or put the `channel-list` on a separate page and after selecting a channel, navigate to the message view. (_This might be possible as is, but the documentation only shows keeping all the stream chat components in the same spot_)

Also, when viewing image attachments, it opens a modal. Looking through the docs, I see a way to use the modal as a tool to show whatever content the developer wants. But I don't see any way to change what happens when an attachment image is clicked, without creating a custom component for the messages-list. Since our app already has functionality in other areas to show images, being able to tap into those events would be extremely helpful. The same would be helpful for things like message interactions and such that show a popover, that way we could keep the UI consistent across the entire app.

**Comment by szuperaz** [comment]
We're currently working on version 3 and better customization is an important part of this release.

As of version 3 the SDK will have a centralized location to register custom templates and many new customization points, since our documentation is not yet public you can get more information about these features in our source code: https://github.com/GetStream/stream-chat-angular/blob/beta/projects/stream-chat-angular/src/lib/custom-templates.service.ts#L34 (I'm not sure how Ionic's slot system works I only have experience with Angular's [`ng-content`](https://angular.io/api/core/ng-content) system, but the problem with that is that data binding is very limited between the host component and slot content, in your example, the unread badge template should receive the unread count but it's much harder to achieve with slots than it's with template outlets)

About the specific problems you mentioned
- In version 3 it'll be possible to provide your own template for [avatar](https://github.com/GetStream/stream-chat-angular/blob/beta/projects/stream-chat-angular/src/lib/custom-templates.service.ts#L126) - however currently the same avatar template is used for channels and users, do you want to use separate avatars for channels and users?
- The unread count badge template is a good idea, I've created an issue for it https://github.com/GetStream/stream-chat-angular/issues/252, but it might only be done somewhere in May
- The channel list, message list, message input, and thread components all can be used in separate components/pages and rearranged, but you're right the documentation doesn't mention this (also it's possible that you'd encounter problems with our CSS rules - something that will be addressed in our new theming system and CSS architecture)
- We plan to add the option to override templates for specific attachment types (so you can override templates only for image attachments for example) - this way it's possible to add click handlers to image attachments (this is the issue for the feature: https://github.com/GetStream/stream-chat-angular/issues/232 - it's expected in April/May)
- As of version 3 you can provide your own custom templates for [message action items ](https://github.com/GetStream/stream-chat-angular/blob/beta/projects/stream-chat-angular/src/lib/custom-templates.service.ts#L158) - that way you could add a popover to the item
- As of version 3 it's also possible to use your own [icons](https://github.com/GetStream/stream-chat-angular/blob/beta/projects/stream-chat-angular/src/lib/custom-templates.service.ts#L134) in the SDK - so it's possible to add a popover to any icon

The release of version 3 is expected in the coming days, I'll let you know when it's out. We'd be happy to hear your feedback about these new features.

**Comment by colesanders** [comment]
It sounds like a lot more customization options are coming and I'm excited to see the changes to css architecture! The attachment overrides and unread component will be awesome to have.

My one concern is that the components seem to be somewhat static. It's either use the built in component, or create a custom one. There's no ability for a dev to make slight tweaks to a built in component, unless they use a custom template and then pull in the same functionality. I used slotting as an example, just because I prefer that method. With using slots, the slotted component would have to have its data bound manually in the parent component. So it would require more setup for devs to utilize that feature, but allow a ton of flexibility. However it wouldn't have to be a slotted component. Having the component allow for ngTemplates would work just as well.

The angular components are mainly a drop in solution and fairly static, with the only customization option being to just replace certain components with custom ones, rather than having them also support an amount of optional tailoring. This works great for developers on a project where a drop in is all that's needed. However it means the components are constrained for those who need more flexibility. For example, if the only tweak needed is to have a different image show for the channel preview besides the one on the channel, the developer has to create an entire custom component that is identical to the existing one, but with a different url for the preview. Having different components for channels and user might help some developers, but it would be much easier if the components had inputs that overrode default functionality. That would avoid the complexity of having templates for every piece of functionality. 

Using channel preview as an example for consistency, if it had an optional input for the avatar image that just overrode using the channel image, that would accomplish the same thing without having separate templates. Another case might be overriding the preview text, where it defaults to the last message, but a user could pass in a some custom text or a template to override.

```html
<stream-channel-preview avatarImage="someImageUrl" previewText="Channel Preview Text"></stream-channel-preview>
```

Exposing a level of control over individual stream components would make them super flexible for developers that just need basic changes. Then if developers need more fine grain control, they can use the custom templates. But this way there's a middle ground.

**Comment by szuperaz** [comment]
I agree that developers should have more fine-grained control over component customization, we are introducing those in iterations balancing development with new features and customization options.

Don't hesitate to open new issues if you have any more feedback for us, we are using those to determine the development roadmap for our SDK.

**Comment by szuperaz** [comment]
Version 3 is now released, we also have an [upgrade guide from v2](https://getstream.io/chat/docs/sdk/angular/basics/upgrade-v2/).
