### ISSUE TITLE
Channel Header Component Customization

### ISSUE THREAD

**Issue by JumaBok** [GetStream/stream-chat-angular#301]
The channel header documentation for the Angular components states that it can be customised using the Custom Templates Service however there is no exported context or subject so I'm struggling to see how...

**Comment by szuperaz** [comment]
There is two way to customize the channel header component:
- Provide your own custom channel header component instead of the default one: https://getstream.io/chat/docs/sdk/angular/concepts/customization/#initial-chat-ui (there is a mistake in the docs on the https://getstream.io/chat/docs/sdk/angular/components/ChannelHeaderComponent/#customization page stating that you need the `CustomTemplatesService` for this, sorry if that mistake was that mislead you, I'll fix this)
- Use the default channel header component but add custom actions to it: https://getstream.io/chat/docs/sdk/angular/components/ChannelHeaderComponent/#channel-actions

Let me know if you have any more questions

**Comment by JumaBok** [comment]
Thanks, it's open one we're going for however unlike other customizable templates where you have an exported context as well as a subject to "next" on with the custom template viewchild, there are no properties / values for custom header - other than the thread header which is naturally something else entirely.... So it looks like we can't actually customize the header using the custom templates service.

**Comment by szuperaz** [comment]
That's right, you can't, that is a mistake in the docs. But if you create your own header, you [can subscribe to the `activeChannel$`](https://getstream.io/chat/docs/sdk/angular/components/ChannelHeaderComponent/#customization) in the `ChannelService` to receive the necessary context in your component.

**Comment by JumaBok** [comment]
Thanks, we could do with an updated version of the Angular example App - depending on the version you use, you may or may not have the custom template service etc.

**Comment by szuperaz** [comment]
Thanks for your feedback, it's on our backlog to create versioned documentation, right now you can find the older versions of the example application via GitHub https://github.com/GetStream/stream-chat-angular/releases
