### ISSUE TITLE
Loading indicator causes layout jumps

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#577]
https://github.com/GetStream/stream-chat-angular/assets/25200186/c7f06248-a4db-41fc-9ccc-71547a46f592

It's easily fixable with CSS
```
.str-chat__message-list-scroll {
  // Make room for the loading indicator.
  padding-top: 20px !important;

  stream-loading-indicator {
    // Avoid UI shift.
    height: 0;
    display: block;
    // Move it on the parent's top padding.
    translate: 0 -16px;
  }
}
```

P. S. Also weird that the scroll up triggers loading every time even after you loaded everything already.

**Comment by szuperaz** [comment]
I can't play the video, but I know what you mean.

The problem is that since the loading indicator can be customized, we'd most likely need to use CSS variables to solve this issue, so I don't think it will be solved in the near future.

As for loading is triggered after everything is loaded: that will be solved as part of this issue: https://github.com/GetStream/stream-chat-angular/issues/566
