### ISSUE TITLE
Emoji picker is absent though the empty element takes up space

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#579]
<img width="1116" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/25200186/a9665748-4fd9-4443-84cf-06cc0dc43ee5">

**Comment by ilyakonrad** [comment]
Will the emoji picker be available eventually?

**Comment by szuperaz** [comment]
No, probably not. In general, we try to avoid using third-party libraries as much as possible (for bundle size and maintainability reasons), especially for features that not every integrator needs. And since this "plugin" method works fine for this particular feature without too much overhead, it seems like a more flexible solution.

**Comment by ilyakonrad** [comment]
What do you mean by "plugin method"?

**Comment by szuperaz** [comment]
This is what I mean by it: https://getstream.io/chat/docs/sdk/angular/code-examples/emoji-picker/

**Comment by ilyakonrad** [comment]
Got it, thanks!
